
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace SentimentConsole
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            SentimentModel.ModelInput sampleData = new SentimentModel.ModelInput()
            {
                Text = @"küçük geldi ama çok güzel.",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = SentimentModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");


            Console.WriteLine($"Label: {true}");
            Console.WriteLine($"Text: {@"küçük geldi ama çok güzel."}");


            Console.WriteLine($"\n\nPredicted Label: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
