// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240106090234_ProductConfig")]
    partial class ProductConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtCreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("/images/default.jpg");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtCreatedDate = new DateTime(2024, 1, 6, 12, 2, 34, 240, DateTimeKind.Local).AddTicks(8165),
                            ImageURL = "/images/1.jpg",
                            Name = "Laptop",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 2,
                            AtCreatedDate = new DateTime(2024, 1, 6, 12, 2, 34, 240, DateTimeKind.Local).AddTicks(8177),
                            ImageURL = "/images/2.jpg",
                            Name = "Smartphone",
                            Price = 800m
                        },
                        new
                        {
                            Id = 3,
                            AtCreatedDate = new DateTime(2024, 1, 6, 12, 2, 34, 240, DateTimeKind.Local).AddTicks(8179),
                            ImageURL = "/images/3.jpg",
                            Name = "Headphones",
                            Price = 100m
                        },
                        new
                        {
                            Id = 4,
                            AtCreatedDate = new DateTime(2024, 1, 6, 12, 2, 34, 240, DateTimeKind.Local).AddTicks(8180),
                            ImageURL = "/images/4.jpg",
                            Name = "Tablet",
                            Price = 600m
                        },
                        new
                        {
                            Id = 5,
                            AtCreatedDate = new DateTime(2024, 1, 6, 12, 2, 34, 240, DateTimeKind.Local).AddTicks(8181),
                            ImageURL = "/images/5.jpg",
                            Name = "Smartwatch",
                            Price = 300m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
